export const PROJECT_EXPORT_SCHEMAS = {
  aiops: null,
  ailogscope: 'datasnare-ailogscope/events-v1',
  aiperf: 'datasnare-aiperf/events-v1',
  aiprocmon: 'datasnare-aiprocmon/events-v1',
  airca: 'datasnare-rootcause/investigation-v1',
  ainetscope: 'datasnare-ainetscope/analysis-v1',
  core: null,
};

export const PROJECT_BROWSER_APIS = {
  ailogscope: 'DataSnareAILogScope',
  aiperf: 'DataSnareAIPerf',
  aiprocmon: 'DataSnareAIProcMon',
  airca: 'DataSnareAIRootCause',
  ainetscope: 'DataSnareAINetScope',
};

export const PROJECT_WEB_MIGRATIONS = {
  ailogscope: { frontend: 'react', backend: 'python', status: 'contract-ready', ingest: ['log', 'txt', 'json', 'yaml', 'pdf'] },
  aiperf: { frontend: 'react', backend: 'python', status: 'contract-ready', ingest: ['blg', 'csv', 'xml'] },
  aiprocmon: { frontend: 'react', backend: 'python', status: 'contract-ready', ingest: ['pml', 'csv', 'xml'] },
  ainetscope: { frontend: 'react', backend: 'python', status: 'contract-ready', ingest: ['pcap', 'pcapng', 'cap'] },
};

export const projects = [
  {
    id: 'aiops',
    name: 'DataSnare-AIOps',
    category: 'Operations platform',
    description: 'Monitor systems, investigate incidents, and orchestrate approved remediation.',
    path: '/aiops',
    license: 'Active',
    accent: 'mint',
    capabilities: ['identity-handoff', 'tenant-context', 'approval-actions'],
    details: { tagline: 'Monitor systems, investigate incidents, and orchestrate approved remediation.', inputs: ['Telemetry, metrics, processes, logs, and inventory', 'Alerts, changes, incidents, and remediation results', 'Partner context from services such as NinjaOne'], highlights: ['Real-time monitoring and custom dashboards', 'Local anomaly detection, predictive maintenance, and AI playbooks', 'Approval-aware remediation, ticketing, notifications, and audit history'], workflow: 'Observe tenant systems, correlate operational signals, investigate an incident, then request and approve controlled remediation with an audit trail.', caveat: 'AIOps remains the existing operational platform and source of agent telemetry; Core consumes its context through authenticated APIs rather than direct database access.' },
  },
  {
    id: 'ailogscope',
    name: 'DataSnare-AILogScope',
    category: 'Log intelligence',
    description: 'Normalize event logs and application evidence into explainable findings.',
    path: '/ailogscope',
    license: 'Active',
    accent: 'amber',
    browserApi: PROJECT_BROWSER_APIS.ailogscope,
    exportSchema: PROJECT_EXPORT_SCHEMAS.ailogscope,
    capabilities: ['local-evidence-import', 'normalized-event-export'],
    webMigration: PROJECT_WEB_MIGRATIONS.ailogscope,
    details: { tagline: 'Normalize application logs and Windows event evidence into explainable findings.', inputs: ['.log, .txt, .json, .csv, .ndjson, and converted EVTX'], highlights: ['Log4j and Log4j2 records with stack-trace continuations', 'UTF-8 and UTF-16 detection with bounded evidence retention', 'Deterministic error, restart, service, and failed-logon findings'], workflow: 'Import local evidence, review normalized events and findings, then export datasnare-ailogscope/events-v1.', caveat: 'Native EVTX conversion remains a local PowerShell step; the web migration adds queued Python ingestion.' },
  },
  {
    id: 'aiperf',
    name: 'DataSnare-AIPerf',
    category: 'Performance analysis',
    description: 'Review Performance Monitor captures and identify resource pressure.',
    path: '/aiperf',
    license: 'Active',
    accent: 'blue',
    browserApi: PROJECT_BROWSER_APIS.aiperf,
    exportSchema: PROJECT_EXPORT_SCHEMAS.aiperf,
    capabilities: ['local-evidence-import', 'normalized-event-export'],
    webMigration: PROJECT_WEB_MIGRATIONS.aiperf,
    details: { tagline: 'Review Performance Monitor captures and identify sustained resource pressure.', inputs: ['Converted Performance Monitor CSV', 'System Diagnostics report.xml', 'Native .blg through the web job boundary'], highlights: ['CPU, memory, disk, network, and TCP metric series', 'Sustained threshold findings with observed extremes and windows', 'Locale-aware PDH timestamps and normalized events export'], workflow: 'Convert or upload performance evidence, inspect source metrics and findings, then export datasnare-aiperf/events-v1.', caveat: 'Binary BLG decoding uses the planned Python/native conversion worker; the browser path remains CSV/XML.' },
  },
  {
    id: 'aiprocmon',
    name: 'DataSnare-AIProcMon',
    category: 'Process investigation',
    description: 'Trace process activity, failures, and slow operations from ProcMon exports.',
    path: '/aiprocmon',
    license: 'Active',
    accent: 'coral',
    browserApi: PROJECT_BROWSER_APIS.aiprocmon,
    exportSchema: PROJECT_EXPORT_SCHEMAS.aiprocmon,
    capabilities: ['local-evidence-import', 'normalized-event-export', 'process-map-export'],
    webMigration: PROJECT_WEB_MIGRATIONS.aiprocmon,
    details: { tagline: 'Investigate process activity, failures, and slow operations from ProcMon evidence.', inputs: ['ProcMon CSV and XML exports', 'Native .pml through the web job boundary'], highlights: ['Streaming large CSV imports with bounded salient evidence', 'Access, sharing, path, duration, and process findings', 'Optional TCP/UDP process-map observations'], workflow: 'Convert or upload ProcMon evidence, review deterministic findings and process context, then export datasnare-aiprocmon/events-v1.', caveat: 'Keep the original PML/CSV as primary evidence; normalized exports retain aggregate and salient records.' },
  },
  {
    id: 'airca',
    name: 'DataSnare-AIRootCause',
    category: 'Root cause analysis',
    description: 'Combine normalized evidence into an incident narrative and next actions.',
    path: '/airca',
    license: 'Active',
    accent: 'violet',
    browserApi: PROJECT_BROWSER_APIS.airca,
    exportSchema: PROJECT_EXPORT_SCHEMAS.airca,
    capabilities: ['local-evidence-import', 'investigation-export'],
    details: { tagline: 'Correlate network, performance, process, and log evidence into a time-aligned investigation.', inputs: ['AINetScope analysis and capture-set exports', 'AIPerf, AIProcMon, and AILogScope normalized evidence', 'Generic normalized JSON, timestamped CSV, and text logs'], highlights: ['Unified timeline with clock-offset correction', 'Severity/text filtering, zoom, inspection, and evidence bookmarks', 'Problem statement, hypotheses, root cause, recommended actions, and bundle export'], workflow: 'Import multiple evidence artifacts, align source clocks, inspect timeline relationships, capture bookmarks, and produce a structured investigation report.', caveat: 'AIRootCause remains a local-first browser workspace today; the Core migration will add tenant persistence and federated retrieval.' },
  },
  {
    id: 'ainetscope',
    name: 'DataSnare-AINetScope',
    category: 'Network analysis',
    description: 'Inspect large packet captures, streams, and protocol-level behavior.',
    path: '/ainetscope',
    license: 'Active',
    accent: 'teal',
    browserApi: PROJECT_BROWSER_APIS.ainetscope,
    exportSchema: PROJECT_EXPORT_SCHEMAS.ainetscope,
    capabilities: ['local-evidence-import', 'network-flow-export'],
    webMigration: PROJECT_WEB_MIGRATIONS.ainetscope,
    details: { tagline: 'Inspect large packet captures, streams, and protocol behavior.', inputs: ['.pcap, .pcapng, and .cap captures', 'Capture sets from dumpcap rotations', 'Normalized process-map observations'], highlights: ['PCAP/PCAPNG protocol, flow, latency, and topology analysis', 'Wireshark-style packet workbench with lazy byte inspection', 'Large-capture compact models, worker parsing, and outlier detection'], workflow: 'Open a local capture for offline triage or queue it through the Core web workbench, then inspect flows, packets, findings, and exports.', caveat: 'The current Python web parser validates capture headers while full packet decoding remains in the local browser analyzer.' },
  },
  {
    id: 'core',
    name: 'DataSnare-Core',
    category: 'Suite control plane',
    description: 'Manage suite identity, access, licensing, and project launch points.',
    path: '/',
    license: 'Included',
    accent: 'ink',
    capabilities: ['project-registry', 'session-handoff', 'partner-integrations'],
  },
];

export function buildProjectLaunchContext(project, account = {}, skin = null) {
  return {
    schema: 'datasnare-core/project-launch-v1',
    issuedAt: new Date().toISOString(),
    project: {
      id: project.id,
      name: project.name,
      path: project.path,
      exportSchema: project.exportSchema || null,
      browserApi: project.browserApi || null,
      capabilities: project.capabilities || [],
      webMigration: project.webMigration || null,
    },
    account: {
      tenantId: account.tenantId || null,
      organizationId: account.organizationId || null,
      actorId: account.actorId || null,
      license: project.license,
    },
    skin,
  };
}