export const PROJECT_EXPORT_SCHEMAS = {
  aiops: null,
  ailogscope: 'datasnare-ailogscope/events-v1',
  aiperf: 'datasnare-aiperf/events-v1',
  aiprocmon: 'datasnare-aiprocmon/events-v1',
  airca: 'datasnare-rootcause/investigation-v1',
  ainetscope: 'datasnare-ainetscope/analysis-v1',
  core: null,
};

export const PROJECT_BROWSER_APIS = {
  ailogscope: 'DataSnareAILogScope',
  aiperf: 'DataSnareAIPerf',
  aiprocmon: 'DataSnareAIProcMon',
  airca: 'DataSnareAIRootCause',
  ainetscope: 'DataSnareAINetScope',
};

export const PROJECT_WEB_MIGRATIONS = {
  ailogscope: { frontend: 'react', backend: 'python', status: 'contract-ready', ingest: ['log', 'txt', 'json', 'yaml', 'pdf'] },
  aiperf: { frontend: 'react', backend: 'python', status: 'contract-ready', ingest: ['blg', 'csv', 'xml'] },
  aiprocmon: { frontend: 'react', backend: 'python', status: 'contract-ready', ingest: ['pml', 'csv', 'xml'] },
  ainetscope: { frontend: 'react', backend: 'python', status: 'contract-ready', ingest: ['pcap', 'pcapng', 'cap'] },
};

export const projects = [
  {
    id: 'aiops',
    name: 'DataSnare-AIOps',
    category: 'Operations platform',
    description: 'Monitor systems, investigate incidents, and orchestrate approved remediation.',
    path: '/aiops',
    license: 'Active',
    accent: 'mint',
    capabilities: ['identity-handoff', 'tenant-context', 'approval-actions'],
  },
  {
    id: 'ailogscope',
    name: 'DataSnare-AILogScope',
    category: 'Log intelligence',
    description: 'Normalize event logs and application evidence into explainable findings.',
    path: '/ailogscope',
    license: 'Active',
    accent: 'amber',
    browserApi: PROJECT_BROWSER_APIS.ailogscope,
    exportSchema: PROJECT_EXPORT_SCHEMAS.ailogscope,
    capabilities: ['local-evidence-import', 'normalized-event-export'],
    webMigration: PROJECT_WEB_MIGRATIONS.ailogscope,
  },
  {
    id: 'aiperf',
    name: 'DataSnare-AIPerf',
    category: 'Performance analysis',
    description: 'Review Performance Monitor captures and identify resource pressure.',
    path: '/aiperf',
    license: 'Active',
    accent: 'blue',
    browserApi: PROJECT_BROWSER_APIS.aiperf,
    exportSchema: PROJECT_EXPORT_SCHEMAS.aiperf,
    capabilities: ['local-evidence-import', 'normalized-event-export'],
    webMigration: PROJECT_WEB_MIGRATIONS.aiperf,
  },
  {
    id: 'aiprocmon',
    name: 'DataSnare-AIProcMon',
    category: 'Process investigation',
    description: 'Trace process activity, failures, and slow operations from ProcMon exports.',
    path: '/aiprocmon',
    license: 'Active',
    accent: 'coral',
    browserApi: PROJECT_BROWSER_APIS.aiprocmon,
    exportSchema: PROJECT_EXPORT_SCHEMAS.aiprocmon,
    capabilities: ['local-evidence-import', 'normalized-event-export', 'process-map-export'],
    webMigration: PROJECT_WEB_MIGRATIONS.aiprocmon,
  },
  {
    id: 'airca',
    name: 'DataSnare-AIRootCause',
    category: 'Root cause analysis',
    description: 'Combine normalized evidence into an incident narrative and next actions.',
    path: '/airca',
    license: 'Active',
    accent: 'violet',
    browserApi: PROJECT_BROWSER_APIS.airca,
    exportSchema: PROJECT_EXPORT_SCHEMAS.airca,
    capabilities: ['local-evidence-import', 'investigation-export'],
  },
  {
    id: 'ainetscope',
    name: 'DataSnare-AINetScope',
    category: 'Network analysis',
    description: 'Inspect large packet captures, streams, and protocol-level behavior.',
    path: '/ainetscope',
    license: 'Active',
    accent: 'teal',
    browserApi: PROJECT_BROWSER_APIS.ainetscope,
    exportSchema: PROJECT_EXPORT_SCHEMAS.ainetscope,
    capabilities: ['local-evidence-import', 'network-flow-export'],
    webMigration: PROJECT_WEB_MIGRATIONS.ainetscope,
  },
  {
    id: 'core',
    name: 'DataSnare-Core',
    category: 'Suite control plane',
    description: 'Manage suite identity, access, licensing, and project launch points.',
    path: '/',
    license: 'Included',
    accent: 'ink',
    capabilities: ['project-registry', 'session-handoff', 'partner-integrations'],
  },
];

export function buildProjectLaunchContext(project, account = {}, skin = null) {
  return {
    schema: 'datasnare-core/project-launch-v1',
    issuedAt: new Date().toISOString(),
    project: {
      id: project.id,
      name: project.name,
      path: project.path,
      exportSchema: project.exportSchema || null,
      browserApi: project.browserApi || null,
      capabilities: project.capabilities || [],
      webMigration: project.webMigration || null,
    },
    account: {
      tenantId: account.tenantId || null,
      organizationId: account.organizationId || null,
      actorId: account.actorId || null,
      license: project.license,
    },
    skin,
  };
}